version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_LOCAL_PORT}:${DATABASE_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp-network

  app:
    image: papemor221/employee-api:v1.0.0
    container_name: express-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_LOCAL_PORT}:${APP_DOCKER_PORT}"
    depends_on:
      - database
    networks:
      - myapp-network

volumes:
  postgres_data:

networks:
  myapp-network:
    driver: bridge