apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-db
        image: busybox
        command: ['sh', '-c', 'until nc -z database-service 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: backend
        image: papemor221/employee-api-kube:v2.2.0
        #envFrom:
        #  - configMapRef:
        #      name: backend-config
        #  - secretRef:
        #      name: backend-secre
        env:
        - name: DATABASE_HOST
          value: database-service  # Nom du service de la base de données
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "my_database"
        - name: DATABASE_USER
          value: "user"
        - name: DATABASE_PASSWORD
          value: "passer"

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
